# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @useDynLib CB2
#' @export
quant <- function(ref_path, fastq_path) {
    .Call('_CB2_quant', PACKAGE = 'CB2', ref_path, fastq_path)
}

#' @importFrom Rcpp evalCpp
#' @useDynLib CB2
#' @export
fit_ab <- function(xvec, nvec) {
    .Call('_CB2_fit_ab', PACKAGE = 'CB2', xvec, nvec)
}

