# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quant <- function(ref_path, fastq_path) {
    .Call(`_CRISPRExpress_quant`, ref_path, fastq_path)
}

fit_ab <- function(xvec, nvec) {
    .Call(`_CRISPRExpress_fit_ab`, xvec, nvec)
}

